### ISSUE TITLE
open from another device get confuse opencam

### ISSUE THREAD

**Issue by blinkbink** [dxue2012/python-webcam-flask#2]
hello i have problem, exactly 2 problem :
1. when i try visit live demo site on : https://python-stream-video.herokuapp.com/
using 2 device A and B, when i visit the site both with A and B top canvas stream from each device camera, but when i access site from A and B on bottom canvas is open source on cam A and B alternately  not from each device camera, sometimes open from A but source cam open is from , any clue ?
2. i try running on local, but i can't access from another device on same network i run with gunicorn ?

**Comment by dxue2012** [comment]
Sorry I just saw this - 

1. Yeah, this is a known issue. The demo site wasn't really meant for multiple clients to connect. As you can see in the code, the server has no concept of sessions and simply streams data it got from any client back to the webpage. So what you observed isn't that surprising.

2. I think that's a networking issue. If you run it locally, you'd need your local device (and the port the program is running on) to be visible on your network.
